# Generated by Django 6.0.3 on 2026-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'à¤¹à¤¿à¤¨à¥\x8dà¤¦à¥€'), ('Marathi', 'à¤®à¤°à¤¾à¤\xa0à¥€')], default='English', max_length=20),
        ),
    ]
